FROM richarvey/nginx-php-fpm:latest

# https://github.com/ngineered/nginx-php-fpm


WORKDIR /var/www

# RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log
# RUN ln -sf /proc/self/fd/1 /var/log/apache2/error.log
# RUN ln -sf /proc/self/fd/1 /var/log/apache2/other_vhosts_access.log
